# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'KCCM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KCCM

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Functions'

end

